### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by XiaoTailong** [QuanEstimation/QuanEstimation#197]
Direct installation using pip will involve the installation of julia which may have errors since its version is too old (0.5.17). The installation is tried in linux platform. Can you tell me how to install the package in linux and I want to try the code in python language. 
Errors: description:

Cannot import quanestimation package and shows
ERROR: could not load library "/home/~/.local/bin/../lib/julia/sys.so"
/home/~/.local/bin/../lib/julia/sys.so: cannot open shared object file: No such file or directory

**Comment by HM-Yuuu** [comment]
Welcome to the QuanEstimation community, can you try uninstall the old by deleting
