### ISSUE TITLE
Broken (?) output for measurement optimization in LC scenario

### ISSUE THREAD

**Issue by 2absurd** [QuanEstimation/QuanEstimation#212]
Hi everyone,

The following problem occurrs when trying to optimize a quantum measurement, in particular, when optimizing a linear combination of the input operators. In most cases of the LC optimization, the output of the "measurements.csv" does not look correct to me. I am running the code via Python on Windows 10.

Here's a minimal working example based on the [example 7.2](https://quanestimation.github.io/QuanEstimation/examples/Python%20examples/measurement_optimization_qubit.ipynb), if the POVM basis is changed to just the projectors onto the basis states
```python
# initial state
rho0 = 0.5*np.array([[1., 1.], [1., 1.]])
# free Hamiltonian
omega = 1.0
sx = np.array([[0., 1.], [1., 0.]])
sy = np.array([[0., -1.j], [1.j, 0.]]) 
sz = np.array([[1., 0.], [0., -1.]])
H0 = 0.5*omega*sz
# derivative of the free Hamiltonian on omega
dH = [0.5*sz]
# dissipation
sp = np.array([[0., 1.], [0., 0.]])  
sm = np.array([[0., 0.], [1., 0.]]) 
decay = [[sp, 0.], [sm, 0.1]]
# generation of a set of POVM basis
dim = np.shape(rho0)[0]
#POVM from the two basis state projector operators
POVM_basis = [np.dot(basis(dim, i), basis(dim, i).conj().T) for i in range(dim)]
# time length for the evolution
tspan = np.linspace(0., 10., 2500)

# measurement optimization algorithm: AD
AD_paras = {"Adam":False, "measurement0":[], "max_episode":300, \
            "epsilon":0.01, "beta1":0.90, "beta2":0.99}
m = MeasurementOpt(mtype="input", minput=["LC", POVM_basis, 2], \
                   savefile=False, method="AD", **AD_paras)

```
If I understand correctly, for an LC consisting of `m` operators and with a POVM of `n` operators, the output should be an '(m x n)' complex matrix.  In my case, the output should thus be a 2-row 2-column "measurements.csv" file, but what I get is the following:
```
0.3043628221299947+0.0j	0.0+0.0j	0.0+0.0j	0.442005826237257+0.0j
0.6956371778700052+0.0j	0.0+0.0j	0.0+0.0j	0.5579941737627431+0.0j
```
with four columns instead of two. 

In the original version of the code, SIC POVM with 4 operators is used, which produces what seems to be the correct output

```python
POVM_basis = SIC(dim)
```

```
0.5000000000000001+0.0j	2.7755575615628914e-17+0.2886751345948132j	2.7755575615628914e-17-0.2886751345948132j	0.5+0.0j
0.5000000000000001+0.0j	2.7755575615628914e-17-0.28867513459481325j	2.7755575615628914e-17+0.28867513459481325j	0.5000000000000001+0.0j
```

Another example, if I am running a linear combination optimization of Example 7.3, then even without making any changes in the [code](https://quanestimation.github.io/QuanEstimation/examples/Python%20examples/measurement_optimization_NV.ipynb), instead of a 4x6 complex matrix of coefficients, I get the following:
```
0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	1.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	1.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j
0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	1.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j
0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	1.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	1.0+0.0j
1.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j	0.0+0.0j

```

The issue occurs for all of the available algorithms and adding an initial guess `measurement0` also does not seem to help. Is there any way to interpret this output or is this a bug?

**Comment by zhangmao2018** [comment]
Welcome to the QuanEstimation community, and feel free to submit issues and pull requests.
In the LC scenario, the optimization returns a list of complex matrices (the dimension of each matrix is dim*dim) with a length equals to n, not a ‘(m x n)’ complex matrix.
Each complex matrix in the list represents a POVM, and is flattened into single line and then stored in the “measurements.csv” file. So what we get is not the coefficients but the optimized POVM.
Here’s a code which can transfer “measurements.csv” to “measurements.npy”, and then load it.
``` python
M_num = n
M_= np.loadtxt(“measurements.csv”, dtype=np.complex128)
csv2npy_measurements(M_, M_num)
# load the measurements
M = np.load(“measurements.npy”)[-1]
```
here, `M` is a set of optimal measurements obtained by QuanEstimation.
In the example 7.3, the output is a list of matrices with the length equals to 4, and the dimension of each matrix in the list is 6*6. Similarly, we can use the codes above to convert the flattened data in the “measurements.csv” into “measurements.npy” for further use.
You have mentioned that the output of the example 7.3 is the same regardless of the algorithm used. The reason for this is that this set of measurements is the optimal one in the LC scenario. You can try to set the variable `savefile=True` , and convert the results by the code
``` python
M_num = n
M_= np.loadtxt(“measurements.csv”, dtype=np.complex128)
csv2npy_measurements(M_, M_num)
```
and load the measurements for each episode with
`M = np.load(“measurements.npy”)[i]`
here, “i” represents the ith episode. It can be found that the measurements are updated with the iterations and eventually converge to the optimal one.
Thank you again for your question and I hope the answers are helpful to you. Besides, we will update the data conversion code into examples in the documentations later.

**Comment by zhangmao2018** [comment]
If there are multiple sets of POVMs in the "measurements.csv", please put the function `csv2npy_measurements` in your test code: 
```python
def csv2npy_measurements(M, num):
    n = int(np.sqrt(len(M[0])))
    N = int(len(M) / num)
    M_save = []
    for mi in range(N):
        M_tp = M[mi * num : (mi + 1) * num]
        M_mi = [M_tp[i].reshape(n, n).T for i in range(num)]
        M_save.append(M_mi)
    np.save("measurements", M_save)
```
