### ISSUE TITLE
Installation on Mac M2 fails

### ISSUE THREAD

**Issue by ahfs** [QuanEstimation/QuanEstimation#231]
I have followed the instructions to install this QuanEstimation on my M2 Mac. 
It worked up the final step where I try to import it into Python. 
I chose "n" for building the image. 
And here is the error message I got:

` Exception: Instantiation of project failed, no Manifest.toml created in XXXX/miniforge3/envs/quantum/julia_project/quanestimation-1.10.0.` 

Appreciate your help with this. 

Here is everything it prints when it gives the error:

myMac ~ % python3
Python 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:35:25) [Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from quanestimation import *

I can compile a system image after installation.
Compilation may take a few, or many, minutes. You may compile now, later, or never.
Would you like to compile a system image after installation?
 [Y/n] n
Instantiating project...
  Activating project at `XXXX/miniforge3/envs/quantum/julia_project/quanestimation-1.10.0`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package CUDA [052768ef]:
 CUDA [052768ef] log:
 ├─possible versions are: 0.1.0-5.3.3 or uninstalled
 ├─restricted by julia compatibility requirements to versions: [2.3.0, 2.5.0-5.3.3] or uninstalled
 ├─restricted by compatibility requirements with GPUCompiler [61eb1bfa] to versions: 5.0.0-5.3.3 or uninstalled
 │ └─GPUCompiler [61eb1bfa] log:
 │   ├─possible versions are: 0.1.0-0.26.4 or uninstalled
 │   └─restricted by julia compatibility requirements to versions: 0.22.0-0.26.4 or uninstalled
 └─restricted by compatibility requirements with ReinforcementLearningZoo [d607f57d] to versions: 3.0.0-3.13.1 — no versions left
   └─ReinforcementLearningZoo [d607f57d] log:
     ├─possible versions are: 0.1.0-0.9.0 or uninstalled
     ├─restricted by compatibility requirements with CUDA [052768ef] to versions: [0.1.0-0.1.4, 0.2.2-0.9.0] or uninstalled
     │ └─CUDA [052768ef] log: see above
     ├─restricted by compatibility requirements with Zygote [e88e6eb3] to versions: 0.3.2-0.9.0 or uninstalled
     │ └─Zygote [e88e6eb3] log:
     │   ├─possible versions are: 0.1.0-0.6.69 or uninstalled
     │   └─restricted by compatibility requirements with QuanEstimation [088c8dff] to versions: 0.6.0-0.6.69
     │     └─QuanEstimation [088c8dff] log:
     │       ├─possible versions are: 0.1.0-0.1.5 or uninstalled
     │       └─restricted to versions 0.1.5-0.1 by an explicit requirement, leaving only versions: 0.1.5
     └─restricted by compatibility requirements with ReinforcementLearning [158674fc] to versions: 0.5.0-0.5.12
       └─ReinforcementLearning [158674fc] log:
         ├─possible versions are: 0.2.0-0.11.0 or uninstalled
         └─restricted by compatibility requirements with QuanEstimation [088c8dff] to versions: 0.10.0-0.10.2
           └─QuanEstimation [088c8dff] log: see above
Stacktrace:
  [1] propagate_constraints!(graph::Pkg.Resolve.Graph, sources::Set{Int64}; log_events::Bool)
    @ Pkg.Resolve /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Resolve/graphtype.jl:1072
  [2] propagate_constraints! (repeats 2 times)
    @ Pkg.Resolve /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Resolve/graphtype.jl:1008 [inlined]
  [3] simplify_graph!(graph::Pkg.Resolve.Graph, sources::Set{Int64}; clean_graph::Bool)
    @ Pkg.Resolve /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Resolve/graphtype.jl:1533
  [4] simplify_graph! (repeats 2 times)
    @ Pkg.Resolve /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Resolve/graphtype.jl:1532 [inlined]
  [5] resolve_versions!(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, julia_version::VersionNumber, installed_only::Bool)
    @ Pkg.Operations /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:407
  [6] targeted_resolve(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, preserve::Pkg.Types.PreserveLevel, julia_version::VersionNumber)
    @ Pkg.Operations /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1360
  [7] tiered_resolve(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, julia_version::VersionNumber, try_all_installed::Bool)
    @ Pkg.Operations /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1349
  [8] _resolve(io::Base.PipeEndpoint, env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, preserve::Pkg.Types.PreserveLevel, julia_version::VersionNumber)
    @ Pkg.Operations /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1370
  [9] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, new_git::Set{Base.UUID}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform)
    @ Pkg.Operations /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1387
 [10] add
    @ /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1376 [inlined]
 [11] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::@Kwargs{io::Base.PipeEndpoint})
    @ Pkg.API /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/API.jl:278
 [12] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.PipeEndpoint, kwargs::@Kwargs{})
    @ Pkg.API /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/API.jl:159
 [13] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/API.jl:148
 [14] add
    @ Pkg.API /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/API.jl:147 [inlined]
 [15] add(pkg::String)
    @ Pkg.API /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/Pkg/src/API.jl:146
 [16] top-level scope
    @ none:1
Initialization failed. You may try running again
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "XXXX/miniforge3/envs/quantum/lib/python3.10/site-packages/quanestimation/__init__.py", line 8, in <module>
    project.ensure_init()
  File "XXXX/miniforge3/envs/quantum/lib/python3.10/site-packages/julia_project/_julia_project.py", line 278, in ensure_init
    self.init()
  File "XXXX/miniforge3/envs/quantum/lib/python3.10/site-packages/julia_project/_julia_project.py", line 376, in init
    basic.ensure_project_ready(
  File "XXXX/miniforge3/envs/quantum/lib/python3.10/site-packages/julia_project_basic/basic.py", line 390, in ensure_project_ready
    res = instantiate(project_path, julia_exe=julia_exe, depot_path=depot_path, clog=clog, packages_to_add=the_packages_to_add,
  File "XXXX/miniforge3/envs/quantum/lib/python3.10/site-packages/julia_project_basic/basic.py", line 175, in instantiate
    raise Exception(f"Instantiation of project failed, no Manifest.toml created in {project_path}.")
Exception: Instantiation of project failed, no Manifest.toml created in XXXX/miniforge3/envs/quantum/julia_project/quanestimation-1.10.0.

**Comment by hmyuuu** [comment]
It seems that there's an issue with dependencies compat on the Julia side. 
I'll try my best to fix it.

**Comment by hmyuuu** [comment]
The compat issue is fixed, and the patched version has been uploaded to PyPI.
Please reinstall the new version with `pip install quanestimation`, and try `import` again.

**Comment by hmyuuu** [comment]
@ahfs I hope this works fine for you. 😃

**Comment by ahfs** [comment]
> @ahfs I hope this works fine for you. 😃

Thank you for looking into this, @hmyuuu ! 
I am installing it on Mac M3. And here is the status and what I have done to fix it so far:
1. when pip installing the package, it complained about osqp and failed. I installed osqp using conda successfully, and pip installed quanestimation. that fixed it. 
2. because M3's shell is a zsh, I manually added the installation path to the `.zshrc` and then opened python to import quanestimation. It worked. 
3. when I import quanestimation, it installs julia, etc and it all completes successfully. But then it closes the python env with a segmentation fault error message. 
here is a screenshot:
<img width="556" alt="image" src="https://github.com/QuanEstimation/QuanEstimation/assets/4733869/cbde6f71-d36e-4040-801f-6977b5335a06">

Any idea what could be wrong?

**Comment by hmyuuu** [comment]
Can you check and paste the `quanestimation.log` file under the directory please?

It works with miniforge on my M1 though. 
<img width="749" alt="image" src="https://github.com/QuanEstimation/QuanEstimation/assets/17229820/690a8c89-edb3-463b-9bab-637c97c0f537">

**Comment by ahfs** [comment]
Great. So there must be a way. I am also using miniforge3. Here is the latest log file: 
[quanestimation.log](https://github.com/QuanEstimation/QuanEstimation/files/15289399/quanestimation.log)

**Comment by ahfs** [comment]
@hmyuuu I tried the julia version. That installs without an issue, and I could successfully run the examples in the julia env. The problem is with running the python version. That's where it gives a seg fault error. But Julia works without an issue.

**Comment by hmyuuu** [comment]
I can't reproduce the seg fault error, but it did happen once before when I tried to change the conda env. 
You can try deleting the `julia_env` and `julia_project` under the `~/miniforge3/` directory and install again. 
Or you can check if it works with a new conda env with `conda create -n xxx python=3.10`.

**Comment by ahfs** [comment]
Thank you @hmyuuu! I deleted the julia files in miniforge and installed it fresh in a new conda env with python 3.10 as you suggested and it is working now. 
Thank you for your help!
